on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - 'src/**'
      - 'docs/**'
      - '.github/workflows/push-pr.yml'
  pull_request:
    branches:
      - main
      - "release/**"
    paths:
      - 'src/**'
      - 'docs/**'
      - '.github/workflows/push-pr.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: npm test

        
      